Question.find_or_create_by({text:"What is your skin tone?"})
Question.find_or_create_by({text:"What is your usual lip go-to look?"})
Question.find_or_create_by({text:"What color family do you typically gravitate towards?"})
Question.find_or_create_by({text:"What finished look do you prefer?"})
Answer.find_or_create_by({text:"Cool", question:Question.first})
Answer.find_or_create_by({text:"Warm", question:Question.first})
Answer.find_or_create_by({text:"Neutral", question:Question.first})
Answer.find_or_create_by({text:"I don't know", question:Question.first})
Answer.find_or_create_by({text:"Bold and Bright", question:Question.second})
Answer.find_or_create_by({text:"Sheer hues", question:Question.second})
Answer.find_or_create_by({text:"Neutrals", question:Question.second})
Answer.find_or_create_by({text:"Only lip balm", question:Question.second})
Answer.find_or_create_by({text:"Pinks", question:Question.third})
Answer.find_or_create_by({text:"Peach or coral", question:Question.third})
Answer.find_or_create_by({text:"Reds", question:Question.third})
Answer.find_or_create_by({text:"Nudes and neutrals", question:Question.third})
Answer.find_or_create_by({text:"Plums and purples", question:Question.third})
Answer.find_or_create_by({text:"Glossy", question:Question.fourth})
Answer.find_or_create_by({text:"Matte", question:Question.fourth})
Answer.find_or_create_by({text:"Frosted", question:Question.fourth})
Answer.find_or_create_by({text:"Something fun", question:Question.fourth})